
name: Webhook - Build

on:
  push:
    branches: [ main ]
    paths:
      - '**incremental.json'
  #pull_request:
    #branches: [ main ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    #environment: test
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
    - name: Slack Notification
      uses: act10ns/slack@v1
      with: 
        status: starting
        channel: '#general'
        #message: Starting Build and Deploy...
        message: Build branch Successfully
      if: always()
           
      
    #- name: Slack Notification
      #uses: act10ns/slack@v1
      #with: 
        #status: ${{ job.status }}
        #channel: '#general'
        #message: Build branch Successfully
      #if: always()
