
name: Webhook - Build

on:
  push:
    branches: [ main ]
    paths:
      - '**incremental.json'
  #pull_request:
    #branches: [ main ]
  pull_request:
    types:
      - opened
    paths:
      - '**.js' 
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    #environment: test
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
    - name: Slack Notification
      uses: act10ns/slack@v1
      id: cpr
      with: 
        status: starting
        channel: '#general'
        #message: Starting Build and Deploy...
        #if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      if: always()
           
      
    #- name: Slack Notification
      #uses: act10ns/slack@v1
      #with: 
        #status: ${{ job.status }}
        #channel: '#general'
        #message: Build branch Successfully
      #if: always()
      
